// scripts/migrate-reason-copy.ts — ONE-TIME migration, kept in the repo as the record.
//
//   npx tsx scripts/migrate-reason-copy.ts          # dry run, prints the diff
//   npx tsx scripts/migrate-reason-copy.ts --write  # applies it
//
// WHY THIS EXISTS AT ALL: riskReasons are generated by lib/scoring.ts but they
// are STORED, verbatim, inside every data/brands/*.json. So fixing the generator
// fixes nothing that already shipped — the 80 live brand pages keep serving the
// old strings until the store is rewritten or the whole corpus is re-converted.
// A re-convert is an EXTRACTION_PRIMARY batch run and would churn every field in
// every file; this touches only the four strings the lint flagged, so the diff
// Jason reviews in GitHub Desktop is exactly the copy change and nothing else.
//
// The transforms below MUST stay in lockstep with lib/scoring.ts. If they drift,
// lib/reasonCopy.test.ts goes red — which is the point of writing the lint first.
//
// BRAND-JSON-EXEMPT: this edits brand files as TEXT — it substitutes encoded
// string literals in the raw bytes and never parses-then-reserializes. That is
// why it does not call serializeBrandRecord: it cannot impose a format, because
// it never emits one. Every byte it does not deliberately change is preserved,
// which is a stronger guarantee than round-tripping, not a weaker one. It does
// JSON.parse the result twice, before writing, purely to prove the edit still
// yields valid JSON carrying the migrated strings.

import fs from "node:fs";
import path from "node:path";

const DIR = path.join(process.cwd(), "data", "brands");
const WRITE = process.argv.includes("--write");

/** Kept in sync with lib/scoring.ts PAYBACK_NOT_MEANINGFUL_YEARS. */
const PAYBACK_NOT_MEANINGFUL_YEARS = 40;

function migrate(text: string): string {
  let out = text;

  // 1 · strip published cutoffs: "(below 1.25)", "(above 25%)"
  out = out.replace(/\s*\((?:below|above|under|over)\s+\$?[\d.,]+%?\)/gi, "");

  // 2 · unsourced market claim → the disclosed figure
  out = out.replace(
    /^Above-market royalty at ([\d.]+)%\.$/i,
    "Royalty runs $1% of gross revenue — verify what that leaves at the bottom line.",
  );

  // 3 · implausible payback → honest non-computation
  const pb = out.match(/^Long payback: ~([\d.]+) years on the build-out before financing\.$/i);
  if (pb && parseFloat(pb[1]) > PAYBACK_NOT_MEANINGFUL_YEARS) {
    out =
      "Payback on the build-out is not meaningfully computable — modeled mid-cohort earnings are too thin to amortize the investment over any realistic horizon.";
  }

  return out;
}

/** Rewrite every riskReasons array at any nesting depth. Returns change count. */
function walk(node: unknown, onChange: (before: string, after: string) => void): void {
  if (!node || typeof node !== "object") return;
  const obj = node as Record<string, unknown>;
  for (const [k, v] of Object.entries(obj)) {
    if (k === "riskReasons" && Array.isArray(v)) {
      obj[k] = v.map((r) => {
        const before = String(r);
        const after = migrate(before);
        if (after !== before) onChange(before, after);
        return after;
      });
    } else {
      walk(v, onChange);
    }
  }
}

/**
 * Encode a JS string the way the store already encodes it: JSON escaping, with
 * every non-ASCII codepoint as \uXXXX.
 *
 * This matters more than it looks. The obvious implementation of this migration
 * is parse → mutate → JSON.stringify(json, null, 2), and it is WRONG: round-
 * tripping reformats all 83 files (verified — zero survive byte-identical),
 * because the store escapes non-ASCII as \\uXXXX where JSON.stringify emits the
 * literal character. That turns a 23-line copy diff into an 83-file rewrite that no human
 * can review, in a repo where the review step IS Jason reading the diff in
 * GitHub Desktop before he commits. So: surgical replacement on the raw text.
 */
function enc(s: string): string {
  return JSON.stringify(s)
    .slice(1, -1)
    .replace(/[^\x20-\x7E]/g, (c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0"));
}

/** Flatten every riskReasons string in a parsed brand file. */
function collectAll(node: unknown, sink: string[]): void {
  if (!node || typeof node !== "object") return;
  for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
    if (k === "riskReasons" && Array.isArray(v)) sink.push(...v.map(String));
    else collectAll(v, sink);
  }
}

let filesTouched = 0;
let stringsChanged = 0;

for (const f of fs.readdirSync(DIR).filter((x) => x.endsWith(".json"))) {
  const p = path.join(DIR, f);
  const raw = fs.readFileSync(p, "utf8");
  const changes: Array<[string, string]> = [];
  walk(JSON.parse(raw), (b, a) => changes.push([b, a]));
  if (!changes.length) continue;

  let next = raw;
  for (const [b, a] of changes) {
    const from = enc(b);
    if (!next.includes(from)) throw new Error(`${f}: could not locate encoded string:\n  ${from}`);
    next = next.split(from).join(enc(a));
  }

  // Prove the edit before it lands: still valid JSON, and the migrated strings
  // actually made it in.
  const after: string[] = [];
  walk(JSON.parse(next), () => {});
  collectAll(JSON.parse(next), after);
  for (const [, a] of changes) {
    if (!after.includes(a)) throw new Error(`${f}: post-migration verify failed for:\n  ${a}`);
  }

  filesTouched++;
  stringsChanged += changes.length;
  console.log(`\n${f}`);
  for (const [b, a] of changes) console.log(`  -  ${b}\n  +  ${a}`);

  if (WRITE) fs.writeFileSync(p, next, "utf8");
}

console.log(
  `\n${WRITE ? "WROTE" : "DRY RUN"} — ${stringsChanged} strings across ${filesTouched} files.`,
);
if (!WRITE) console.log("Re-run with --write to apply.");
